/* =============================================================
   AFA – Mises en situation : assurances non-vie (module 3)
   Chaque question est autonome : elle porte son propre énoncé
   dans le champ `ctx`, affiché au-dessus de la question.
   Marquées lvl:'cas'.
   ============================================================= */
(function () {
  const add = (mid, list) => {
    const m = (window.AFA_MODULES || []).find(x => x.id === mid);
    if (m) m.questions.push(...list.map(q => ({ ...q, lvl: 'cas' })));
  };

  add('m3', [
    /* ---------- c1 : ménage ---------- */
    { id: 'm3k01', chap: 'c1', type: 'single',
      ctx: "Madame Rey habite un 4 pièces à Fribourg. Son inventaire vaut CHF 150 000.–, mais elle l'a assuré pour CHF 100 000.– afin de payer une prime plus basse. Un incendie de cuisine détruit du mobilier pour CHF 18 000.–. La franchise contractuelle est de CHF 500.–.",
      q: "Quel montant l'assureur va-t-il lui verser ?",
      choices: ["CHF 17 500.–", "CHF 12 000.–", "CHF 11 500.–", "CHF 18 000.–"],
      answer: [2],
      explain: "Sous-assurance : 18 000 × (100 000/150 000) = CHF 12 000.–, puis franchise : 12 000 − 500 = CHF 11 500.–. L'économie de prime se paie au moment du sinistre." },

    { id: 'm3k02', chap: 'c1', type: 'single',
      ctx: "Monsieur Baumann rentre de vacances et découvre que sa porte d'entrée a été forcée. Un ordinateur, une montre et de l'argent liquide ont disparu. Il annonce le sinistre le jour même et dépose plainte.",
      q: "Quelle couverture de son assurance ménage est concernée ?",
      choices: ["Le vol simple à l'extérieur", "Le vol par effraction", "Les dégâts d'eau", "La responsabilité civile privée"],
      answer: [1],
      explain: "L'entrée forcée dans un local fermé caractérise l'effraction. Le vol simple à l'extérieur vise les objets dérobés hors du domicile, sans effraction." },

    { id: 'm3k03', chap: 'c1', type: 'single',
      ctx: "Une cliente vous appelle : son sac à main, contenant son porte-monnaie et ses lunettes, lui a été volé pendant qu'elle déjeunait au restaurant. Elle avait posé le sac sur la chaise voisine.",
      q: "Quelle est la situation au regard de son assurance ménage ?",
      choices: ["Rien n'est couvert, il faut une effraction", "C'est du vol simple à l'extérieur, couvert s'il a été souscrit et dans les limites convenues", "C'est couvert par la RC privée", "C'est couvert sans limite de montant"],
      answer: [1],
      explain: "Cette extension existe mais comporte une sous-limite propre et des exigences de diligence. Beaucoup de clients ignorent qu'elle est facultative." },

    { id: 'm3k04', chap: 'c1', type: 'multi',
      ctx: "Monsieur et Madame Perret viennent d'hériter de bijoux estimés à CHF 60 000.–. Leur assurance ménage est fixée à CHF 120 000.– et prévoit une sous-limite de CHF 15 000.– pour les objets de valeur.",
      q: "Quels conseils leur donnez-vous ?",
      choices: ["Faire estimer les bijoux et souscrire une couverture séparée sur liste", "Augmenter la somme d'assurance globale du ménage", "Vérifier les exigences de conservation, par exemple un coffre-fort", "Ne rien faire, la somme globale suffit", "Résilier le contrat ménage"],
      answer: [0, 1, 2],
      explain: "La sous-limite s'applique quelle que soit la somme globale : sans police dédiée, ils ne toucheraient que CHF 15 000.– pour ces bijoux." },

    { id: 'm3k05', chap: 'c1', type: 'single',
      ctx: "Un client part en vacances trois semaines et laisse une fenêtre du rez-de-chaussée entrouverte pour aérer. Des cambrioleurs entrent par cette fenêtre et emportent du matériel pour CHF 9 000.–.",
      q: "Comment l'assureur va-t-il probablement traiter ce sinistre ?",
      choices: ["Indemnisation intégrale", "Réduction de la prestation pour faute grave, sauf clause de renonciation", "Refus total et résiliation", "Prétention frauduleuse"],
      answer: [1],
      explain: "Laisser une ouverture accessible pendant une absence prolongée relève de la négligence grave : l'assureur peut réduire dans la mesure du degré de la faute (art. 14 al. 2 LCA)." },

    { id: 'm3k06', chap: 'c1', type: 'single',
      ctx: "Une machine à laver déborde chez Madame Sanchez, locataire. L'eau abîme son propre parquet flottant posé par ses soins, ainsi que le plafond de la voisine du dessous.",
      q: "Quels contrats interviennent respectivement ?",
      choices: ["Le ménage pour tout", "Le ménage pour ses propres biens, la RC privée pour le dommage à la voisine", "La RC privée pour tout", "L'assurance bâtiment pour tout"],
      answer: [1],
      explain: "On assure ses propres biens en assurance de choses ; le dommage causé à autrui engage la responsabilité civile. La distinction est systématiquement testée." },

    { id: 'm3k07', chap: 'c1', type: 'single',
      ctx: "Monsieur Lehmann a assuré son ménage il y a douze ans pour CHF 90 000.– et n'a jamais rien modifié. Depuis, il a acheté une cuisine équipée, du mobilier design et du matériel de sport. Il estime aujourd'hui son inventaire à CHF 160 000.–.",
      q: "Quel est le risque principal auquel il s'expose ?",
      choices: ["Une prime trop élevée", "Une réduction proportionnelle de l'indemnité sur chaque sinistre", "La nullité du contrat", "Une majoration automatique de la franchise"],
      answer: [1],
      explain: "La sous-assurance s'apprécie au moment du sinistre et s'applique même aux dommages partiels. Une clause d'indexation aurait évité cette dérive." },

    { id: 'm3k08', chap: 'c1', type: 'single',
      ctx: "Le fils de vos clients, 19 ans, part étudier à Lausanne et loue une chambre. Ses parents vous demandent si ses affaires sont couvertes par leur assurance ménage familiale.",
      q: "Que répondez-vous ?",
      choices: ["Elles le sont automatiquement dans tous les cas", "Cela dépend du contrat : de nombreuses polices prévoient une extension pour les enfants logeant hors du domicile, à vérifier", "Elles ne sont jamais couvertes", "Il faut obligatoirement une police séparée"],
      answer: [1],
      explain: "L'extension existe souvent, mais elle est limitée et parfois soumise à conditions : c'est un point de conseil régulièrement oublié lors d'un départ aux études." },

    /* ---------- c2 : bâtiment ---------- */
    { id: 'm3k09', chap: 'c2', type: 'single',
      ctx: "Madame Girard possède une villa dans le canton de Neuchâtel. Un incendie détruit la toiture, et une conduite d'eau encastrée rompt le même hiver, endommageant les murs.",
      q: "Qui prend en charge chacun de ces deux sinistres ?",
      choices: ["L'établissement cantonal pour les deux", "L'établissement cantonal pour l'incendie, un assureur privé pour le dégât d'eau", "Un assureur privé pour les deux", "La commune pour les deux"],
      answer: [1],
      explain: "Neuchâtel connaît un établissement cantonal : le monopole porte sur l'incendie et les dommages naturels. Les dégâts d'eau relèvent du marché privé." },

    { id: 'm3k10', chap: 'c2', type: 'single',
      ctx: "Un propriétaire genevois vous demande de lui proposer l'assurance incendie de son immeuble locatif.",
      q: "Quelle est la situation dans ce canton ?",
      choices: ["Il doit s'affilier à l'établissement cantonal", "Genève fait partie des cantons GUSTAVO : le marché est ouvert aux assureurs privés", "L'assurance incendie y est interdite", "Seule la Confédération peut assurer"],
      answer: [1],
      explain: "GE, UR, SZ, TI, AI, VS et OW n'ont pas d'établissement cantonal : le propriétaire choisit librement son assureur privé." },

    { id: 'm3k11', chap: 'c2', type: 'multi',
      ctx: "Un client vaudois vient de terminer la construction de sa maison. L'assurance de l'établissement cantonal couvre déjà l'incendie et les dommages naturels du bâtiment.",
      q: "Quelles couvertures complémentaires devez-vous lui proposer ?",
      choices: ["Dégâts d'eau du bâtiment", "Bris de glace du bâtiment", "RC du propriétaire d'immeuble", "Installations techniques comme la pompe à chaleur", "Assurance incendie du bâtiment"],
      answer: [0, 1, 2, 3],
      explain: "L'incendie est déjà couvert par le monopole cantonal ; tout le reste demeure au marché privé et constitue votre champ d'action." },

    { id: 'm3k12', chap: 'c2', type: 'single',
      ctx: "Une violente tempête arrache des tuiles sur l'immeuble de votre client. La pluie s'infiltre ensuite et détruit le parquet de deux appartements, qui restent inhabitables quatre mois.",
      q: "Quelles garanties sont mobilisées ?",
      choices: ["Uniquement l'assurance incendie", "Les dommages naturels pour le bâtiment, et la perte de loyer pour les appartements vides", "Uniquement la RC du propriétaire", "L'assurance ménage des locataires uniquement"],
      answer: [1],
      explain: "La tempête relève des dommages naturels ; la perte de loyer compense le revenu locatif pendant la remise en état, à la manière d'une perte d'exploitation." },

    { id: 'm3k13', chap: 'c2', type: 'single',
      ctx: "Un client vous signale qu'un balcon de son immeuble, mal entretenu depuis des années, s'est effondré et a blessé un passant.",
      q: "Sur quelle base sa responsabilité est-elle engagée et quelle assurance intervient ?",
      choices: ["Art. 41 CO, protection juridique", "Art. 58 CO, RC du propriétaire d'immeuble", "Art. 58 LCR, RC véhicule", "Aucune responsabilité, c'est un cas fortuit"],
      answer: [1],
      explain: "Le propriétaire d'ouvrage répond causalement des défauts de construction ou d'entretien, sans qu'une faute personnelle doive être prouvée." },

    { id: 'm3k14', chap: 'c2', type: 'single',
      ctx: "Après un violent séisme dans la région, votre client constate des fissures importantes dans les murs porteurs de sa maison. Il possède une assurance bâtiment ordinaire couvrant incendie et dommages naturels.",
      q: "Sa police intervient-elle ?",
      choices: ["Oui, le séisme fait partie des dommages naturels", "Non, le tremblement de terre est exclu du régime ordinaire", "Oui, à hauteur de 50 %", "Oui, si la maison a moins de dix ans"],
      answer: [1],
      explain: "Le potentiel de cumul du séisme dépasse la capacité du régime ordinaire : sa couverture passe par des solutions spécifiques ou des pools." },

    /* ---------- c3 : véhicules ---------- */
    { id: 'm3k15', chap: 'c3', type: 'single',
      ctx: "Monsieur Fontana, ayant bu plusieurs verres, provoque un accident. Le piéton qu'il renverse subit un dommage de CHF 250 000.–. Sa propre voiture, assurée en casco complète, est détruite (CHF 28 000.–).",
      q: "Comment les deux dommages sont-ils traités ?",
      choices: ["Rien n'est payé, la faute grave exclut tout", "Le piéton est indemnisé intégralement par la RC, avec recours contre M. Fontana ; la casco peut réduire sa prestation pour faute grave", "La RC réduit l'indemnité du piéton", "Seule la casco intervient"],
      answer: [1],
      explain: "Deux logiques distinctes : la protection du lésé est absolue en RC obligatoire, alors que la casco, assurance de ses propres biens, peut être réduite pour faute grave." },

    { id: 'm3k16', chap: 'c3', type: 'single',
      ctx: "Une cliente possède une voiture de six ans, assurée uniquement en RC et casco partielle. En reculant dans un parking, elle heurte un pilier et endommage son propre pare-chocs pour CHF 2 200.–.",
      q: "Qui supporte ce dommage ?",
      choices: ["L'assureur RC", "La casco partielle", "La cliente elle-même", "Le propriétaire du parking"],
      answer: [2],
      explain: "La collision dont on est soi-même responsable n'est couverte que par la casco complète. La RC ne couvre jamais le véhicule de l'assuré." },

    { id: 'm3k17', chap: 'c3', type: 'single',
      ctx: "En rentrant de soirée, votre client trouve sa voiture rayée sur toute la longueur, sur la voie publique. Aucun auteur n'est identifié. Il dispose d'une casco complète avec franchise de CHF 1 000.–, le dommage s'élève à CHF 3 400.–.",
      q: "Quelle indemnité peut-il attendre ?",
      choices: ["CHF 3 400.–", "CHF 2 400.–", "Rien, l'auteur est inconnu", "CHF 1 000.–"],
      answer: [1],
      explain: "Le vandalisme est couvert par la casco complète, indépendamment de l'identification de l'auteur : 3 400 − 1 000 = CHF 2 400.–." },

    { id: 'm3k18', chap: 'c3', type: 'single',
      ctx: "Un chauffard prend la fuite après avoir endommagé la voiture de votre cliente, correctement stationnée. Le véhicule fautif n'a pas pu être identifié. Elle n'a pas de casco.",
      q: "Vers quel organisme l'orientez-vous ?",
      choices: ["Le Bureau national d'assurance", "Le Fonds national de garantie", "La FINMA", "L'Ombudsman de l'assurance"],
      answer: [1],
      explain: "Le Fonds national de garantie intervient pour les véhicules non identifiés ou non assurés ; le Bureau national traite les véhicules immatriculés à l'étranger." },

    { id: 'm3k19', chap: 'c3', type: 'single',
      ctx: "Votre client achète une voiture neuve en leasing. Le contrat de leasing exige une couverture complète du véhicule pendant toute la durée du financement.",
      q: "Quelle couverture devez-vous impérativement prévoir, et pourquoi ?",
      choices: ["La RC seule, car elle est obligatoire", "La casco complète, le bailleur de leasing restant propriétaire du véhicule", "La casco partielle uniquement", "La protection juridique circulation"],
      answer: [1],
      explain: "Le véhicule garantit le financement : seule la casco complète protège sa valeur, y compris en cas de collision dont le conducteur est responsable." },

    { id: 'm3k20', chap: 'c3', type: 'single',
      ctx: "Un client prête sa voiture à son beau-frère pour un déménagement. Celui-ci, distrait, emboutit un véhicule à l'arrêt et cause CHF 12 000.– de dégâts au tiers.",
      q: "L'assurance RC de votre client intervient-elle ?",
      choices: ["Non, seul le détenteur est couvert", "Oui, la RC est attachée au véhicule et couvre les conducteurs autorisés", "Oui, mais uniquement à 50 %", "Non, il fallait une annonce préalable"],
      answer: [1],
      explain: "La RC véhicule protège le lésé quel que soit le conducteur autorisé. Un recours resterait possible en cas de faute grave du conducteur." },

    { id: 'm3k21', chap: 'c3', type: 'single',
      ctx: "Une cliente circule de nuit sur une route de campagne. Un chevreuil surgit et elle le percute : le capot et le radiateur sont endommagés pour CHF 4 800.–. Elle dispose d'une casco partielle, franchise CHF 500.–.",
      q: "Le sinistre est-il couvert ?",
      choices: ["Non, il faut une casco complète", "Oui, la collision avec un animal relève de la casco partielle : indemnité CHF 4 300.–", "Non, c'est un cas de force majeure exclu", "Oui, mais par la RC"],
      answer: [1],
      explain: "La collision avec un animal fait partie des risques subis couverts par la casco partielle : 4 800 − 500 = CHF 4 300.–." },

    { id: 'm3k22', chap: 'c3', type: 'single',
      ctx: "Votre client ne paie pas la prime de sa RC véhicule. L'assureur lui adresse une sommation régulière avec un délai de 14 jours, qui expire sans paiement.",
      q: "Quelle est la conséquence spécifique en assurance RC véhicule ?",
      choices: ["Rien, la couverture est maintenue par la loi", "La couverture est suspendue et l'autorité, informée, fait retirer permis et plaques", "Le contrat est transféré au Fonds national de garantie", "La prime est prélevée d'office sur son compte"],
      answer: [1],
      explain: "L'assurance RC étant une condition de l'immatriculation, sa suspension est annoncée à l'autorité, qui retire l'autorisation de circuler." },

    /* ---------- c4 : RC privée ---------- */
    { id: 'm3k23', chap: 'c4', type: 'single',
      ctx: "Le fils de vos clients, 5 ans, joue au ballon et brise la baie vitrée du voisin. Le dommage s'élève à CHF 2 800.–. À cet âge, l'enfant est considéré comme incapable de discernement.",
      q: "Comment la RC privée familiale traite-t-elle ce cas ?",
      choices: ["Elle refuse : l'enfant n'est pas responsable", "Elle intervient généralement au titre d'une clause d'équité", "Elle exige d'abord la preuve d'une faute des parents", "Elle renvoie vers la protection juridique"],
      answer: [1],
      explain: "Juridiquement l'enfant sans discernement n'est pas responsable et les parents ne le sont que s'ils ont manqué à leur surveillance : la clause d'équité évite que le voisin reste sans indemnisation." },

    { id: 'm3k24', chap: 'c4', type: 'single',
      ctx: "Madame Nussbaum, locataire depuis huit ans, renverse une casserole d'huile brûlante qui abîme définitivement le plan de travail et le sol de la cuisine, propriété du bailleur. Coût de remise en état : CHF 7 500.–.",
      q: "Quelle couverture intervient ?",
      choices: ["Son assurance ménage", "Sa RC privée, garantie des dommages à la chose louée", "L'assurance bâtiment du propriétaire, sans recours", "Aucune, l'usure est exclue"],
      answer: [1],
      explain: "Les installations appartiennent au bailleur : c'est un dommage causé à autrui. Cette garantie comporte souvent une sous-limite qu'il faut vérifier." },

    { id: 'm3k25', chap: 'c4', type: 'single',
      ctx: "Un client vous explique qu'il a démarré une activité accessoire de réparation d'ordinateurs à domicile, le soir et le week-end. Il a endommagé la machine d'un client, qui lui réclame CHF 3 000.–.",
      q: "Sa RC privée couvre-t-elle ce dommage ?",
      choices: ["Oui, puisqu'il travaille chez lui", "Non : l'activité lucrative est exclue, il lui faut une RC professionnelle", "Oui, car l'activité est accessoire", "Oui, jusqu'à CHF 5 000.–"],
      answer: [1],
      explain: "Le caractère accessoire et le lieu d'exercice ne changent rien : dès qu'il y a activité lucrative, la RC privée cesse de couvrir." },

    { id: 'm3k26', chap: 'c4', type: 'single',
      ctx: "Le chien de vos clients, habituellement calme, mord un joggeur qui passait devant leur portail resté ouvert. Le joggeur subit une incapacité de travail de trois semaines et réclame frais médicaux et perte de gain.",
      q: "Quelle base juridique et quelle couverture s'appliquent ?",
      choices: ["Art. 41 CO, protection juridique", "Art. 56 CO, RC privée du détenteur d'animaux", "Art. 58 CO, assurance bâtiment", "Aucune, l'animal a agi seul"],
      answer: [1],
      explain: "L'art. 56 CO institue une responsabilité causale simple du détenteur d'animaux ; la RC privée prend en charge frais médicaux, perte de gain et tort moral." },

    { id: 'm3k27', chap: 'c4', type: 'multi',
      ctx: "Un tiers réclame CHF 60 000.– à votre client pour un dommage que ce dernier conteste fermement, estimant n'avoir commis aucune faute.",
      q: "Que fait concrètement l'assureur RC ?",
      choices: ["Il examine le bien-fondé de la prétention", "Il repousse la réclamation si elle est injustifiée", "Il assume les frais de défense juridique", "Il paie immédiatement pour clore le dossier", "Il résilie le contrat"],
      answer: [0, 1, 2],
      explain: "C'est la fonction passive de la RC : l'assureur devient le bouclier juridique de l'assuré, ce qui a souvent plus de valeur économique que le paiement lui-même." },

    { id: 'm3k28', chap: 'c4', type: 'single',
      ctx: "Lors d'un match de football entre amis, votre client blesse involontairement un adversaire par un tacle appuyé mais conforme au jeu. L'adversaire se fracture la cheville.",
      q: "La RC privée est-elle engagée ?",
      choices: ["Oui, systématiquement dès qu'il y a blessure", "Seulement si une faute est établie : les risques inhérents au jeu sont acceptés par les participants", "Non, le sport est toujours exclu", "Oui, mais uniquement pour le tort moral"],
      answer: [1],
      explain: "Le consentement aux risques normaux du jeu écarte l'illicéité ; un geste d'une brutalité anormale engagerait en revanche la responsabilité." },

    /* ---------- c5 : RC entreprise ---------- */
    { id: 'm3k29', chap: 'c5', type: 'single',
      ctx: "Un employé d'une entreprise de peinture renverse un pot sur le parquet neuf d'un client. La remise en état coûte CHF 6 000.–.",
      q: "Quelle couverture de l'entreprise intervient ?",
      choices: ["L'assurance de choses de l'entreprise", "La RC exploitation", "La perte d'exploitation", "La RC produits"],
      answer: [1],
      explain: "L'employeur répond des dommages causés par ses auxiliaires dans l'accomplissement de leur travail (art. 55 CO) : c'est le cœur de la RC exploitation." },

    { id: 'm3k30', chap: 'c5', type: 'single',
      ctx: "Une PME fabrique des appareils de chauffage. Un défaut de conception provoque un incendie chez un particulier, qui subit CHF 180 000.– de dégâts.",
      q: "Quelle couverture et quelle base juridique ?",
      choices: ["RC exploitation, art. 41 CO", "RC produits, responsabilité causale aggravée de la LRFP", "Perte d'exploitation", "D&O"],
      answer: [1],
      explain: "Le dommage est causé par le produit après sa mise en circulation : la LRFP engage le producteur sans qu'une faute doive être prouvée." },

    { id: 'm3k31', chap: 'c5', type: 'single',
      ctx: "La même PME découvre que 4 000 appareils du même lot présentent ce défaut. Aucun autre dommage n'est encore survenu, mais elle veut les retirer du marché immédiatement. Le retrait coûterait CHF 250 000.–.",
      q: "Quelle couverture peut financer cette opération ?",
      choices: ["La RC produits de base", "L'extension frais de retrait et de rappel", "La perte d'exploitation", "Aucune, il faut attendre un dommage"],
      answer: [1],
      explain: "Sans dommage à un tiers, la RC produits ne s'applique pas encore. Seule l'extension rappel finance l'action préventive, dans une limite propre." },

    { id: 'm3k32', chap: 'c5', type: 'single',
      ctx: "Un architecte commet une erreur de dimensionnement. Le bâtiment ne s'effondre pas, mais le maître d'ouvrage doit engager CHF 90 000.– de travaux correctifs. Aucun bien n'a été détruit, aucune personne blessée.",
      q: "Quelle couverture répond de ce dommage ?",
      choices: ["La RC exploitation", "La RC professionnelle, qui couvre le dommage purement patrimonial", "L'assurance de choses", "La protection juridique"],
      answer: [1],
      explain: "Ni bien détruit ni personne atteinte : c'est un dommage purement financier, que la RC exploitation exclut en principe et que seule la RC professionnelle prend en charge." },

    { id: 'm3k33', chap: 'c5', type: 'single',
      ctx: "Une fiduciaire cesse son activité fin 2026. Son contrat RC professionnelle était en base « claims made », sans couverture subséquente. En 2029, un ancien client lui reproche une erreur commise en 2025.",
      q: "Quelle est la situation ?",
      choices: ["La réclamation est couverte, la faute datant de 2025", "Elle n'est pas couverte : aucun contrat n'était en vigueur au moment de la réclamation", "Elle est couverte à 50 %", "La FINMA prend le relais"],
      answer: [1],
      explain: "C'est le danger du claims made : sans couverture subséquente, la fin du contrat ferme la porte aux réclamations tardives, même pour des faits couverts à l'époque." },

    { id: 'm3k34', chap: 'c5', type: 'multi',
      ctx: "Vous préparez l'offre RC d'une entreprise de construction qui intervient sur des chantiers, creuse des tranchées et emploie quinze personnes.",
      q: "Quels points devez-vous impérativement examiner ?",
      choices: ["RC exploitation pour les travaux chez des tiers", "Dommages aux conduites souterraines", "Dommages à l'objet du travail", "Somme de garantie et sous-limites", "Assurance-vie du dirigeant"],
      answer: [0, 1, 2, 3],
      explain: "L'assurance-vie relève de la prévoyance et d'un autre profil. Conduites souterraines et objet du travail sont deux extensions décisives dans la construction." },

    /* ---------- c6 : choses entreprises ---------- */
    { id: 'm3k35', chap: 'c6', type: 'single',
      ctx: "Un opérateur d'une menuiserie laisse tomber une clé dans une machine à commande numérique en fonctionnement. La machine est détruite : CHF 85 000.–.",
      q: "Quelle assurance intervient ?",
      choices: ["L'assurance incendie", "L'assurance bris de machines", "La RC exploitation", "L'assurance transport"],
      answer: [1],
      explain: "Corps étranger, erreur de manipulation, court-circuit : le bris de machines couvre précisément les dommages soudains et imprévus que l'incendie ignore." },

    { id: 'm3k36', chap: 'c6', type: 'single',
      ctx: "Un incendie détruit l'atelier d'une PME. Sa marge brute annuelle s'élève à CHF 1 200 000.–, mais la somme assurée en perte d'exploitation n'est que de CHF 900 000.–. La perte effective pendant l'arrêt atteint CHF 400 000.–.",
      q: "Quelle indemnité de perte d'exploitation, sans franchise ?",
      choices: ["CHF 400 000.–", "CHF 300 000.–", "CHF 900 000.–", "CHF 360 000.–"],
      answer: [1],
      explain: "Sous-assurance : 900 000/1 200 000 = 75 %. L'indemnité est réduite dans la même proportion : 400 000 × 75 % = CHF 300 000.–." },

    { id: 'm3k37', chap: 'c6', type: 'single',
      ctx: "Une entreprise de textile voit ses ventes s'effondrer de 40 % à la suite d'une crise économique. Aucun sinistre matériel n'est survenu. Le dirigeant vous demande d'activer sa perte d'exploitation.",
      q: "Que répondez-vous ?",
      choices: ["La couverture s'applique, c'est son objet", "Elle ne s'applique pas : un dommage matériel couvert est indispensable pour la déclencher", "Elle s'applique à 50 %", "Elle s'applique après trois mois de carence"],
      answer: [1],
      explain: "C'est la limite fondamentale de cette couverture : sans sinistre matériel préalable assuré, aucune prestation, quelle que soit la réalité de la perte." },

    { id: 'm3k38', chap: 'c6', type: 'single',
      ctx: "L'unique fournisseur de composants d'une PME subit un incendie et cesse de livrer pendant deux mois. La production de votre client est à l'arrêt, alors qu'aucun dommage matériel ne l'a touché.",
      q: "Quelle extension aurait permis de couvrir cette interruption ?",
      choices: ["La carence fournisseur", "Le bris de machines", "La RC produits", "La protection juridique"],
      answer: [0],
      explain: "L'extension carence fournisseur couvre les interruptions dont la cause matérielle se situe chez un partenaire, en dehors de l'entreprise assurée." },

    { id: 'm3k39', chap: 'c6', type: 'single',
      ctx: "Après un incendie, une entreprise a besoin de 16 mois pour reconstruire et retrouver son niveau d'activité. Sa police de perte d'exploitation prévoit une période d'indemnisation de 12 mois.",
      q: "Quelle en est la conséquence ?",
      choices: ["L'assureur indemnise les 16 mois", "L'assureur indemnise 12 mois, les 4 derniers restant à la charge de l'entreprise", "Le contrat est nul", "La période est prolongée d'office"],
      answer: [1],
      explain: "La période d'indemnisation est une limite ferme : elle doit être calibrée sur le temps réel de reconstruction, souvent sous-estimé lors de la souscription." },

    { id: 'm3k40', chap: 'c6', type: 'single',
      ctx: "Une entreprise expédie par la route un lot de marchandises d'une valeur de CHF 60 000.–. Le camion du transporteur se renverse et la marchandise est perdue. La responsabilité du transporteur est plafonnée par le droit du transport.",
      q: "Quelle assurance protège directement le propriétaire de la marchandise ?",
      choices: ["La RC du transporteur uniquement", "L'assurance transport de marchandises", "La perte d'exploitation", "L'assurance bâtiment"],
      answer: [1],
      explain: "L'assurance transport indemnise le propriétaire indépendamment de la responsabilité du transporteur, souvent limitée par kilogramme." },

    /* ---------- c7 : PJ, cyber ---------- */
    { id: 'm3k41', chap: 'c7', type: 'single',
      ctx: "Un client vous appelle : il est en litige avec son bailleur depuis trois mois et souhaite souscrire aujourd'hui une protection juridique pour financer la procédure.",
      q: "Que lui répondez-vous ?",
      choices: ["Le litige sera couvert dès la signature", "Le litige est déjà né : il est exclu, et un délai de carence s'applique aux nouveaux cas", "Il sera couvert après paiement de la prime", "Le contrat sera nul"],
      answer: [1],
      explain: "Assurer un litige déjà survenu supprimerait l'aléa. C'est précisément le rôle du délai de carence et de l'exclusion des cas préexistants." },

    { id: 'm3k42', chap: 'c7', type: 'single',
      ctx: "Votre cliente veut contester une décision dont son propre avocat lui a dit qu'elle n'avait aucune chance d'aboutir. Elle demande à sa protection juridique de financer la procédure.",
      q: "L'assureur peut-il refuser ?",
      choices: ["Non, il doit financer toute procédure", "Oui, une démarche dépourvue de chances de succès peut être refusée", "Non, sauf accord du client", "Oui, mais seulement au-delà de CHF 50 000.–"],
      answer: [1],
      explain: "L'assureur n'a pas à financer une procédure vouée à l'échec. Les conditions prévoient généralement une procédure d'arbitrage en cas de désaccord." },

    { id: 'm3k43', chap: 'c7', type: 'multi',
      ctx: "Une PME de 25 employés est victime d'un rançongiciel : ses serveurs sont chiffrés, l'activité s'arrête cinq jours, et les données de 3 000 clients ont été exfiltrées.",
      q: "Quels postes une assurance cyber peut-elle prendre en charge ?",
      choices: ["L'analyse forensique et la restauration des systèmes", "La perte d'exploitation d'origine cyber", "La communication de crise", "La responsabilité envers les clients dont les données ont fuité", "Les impôts de l'exercice"],
      answer: [0, 1, 2, 3],
      explain: "La cyber est hybride : elle finance à la fois les frais propres de l'entreprise et sa responsabilité envers les personnes lésées." },

    { id: 'm3k44', chap: 'c7', type: 'single',
      ctx: "Lors de la souscription de sa cyber, une entreprise avait déclaré disposer de sauvegardes hors ligne testées régulièrement. Après l'attaque, il apparaît qu'aucune sauvegarde n'existait, ce qui a considérablement aggravé les dégâts.",
      q: "Quelle qualification juridique s'impose ?",
      choices: ["Une simple négligence sans conséquence", "Une réticence : l'assureur peut résilier et refuser la prestation, le fait tu ayant influé sur le sinistre", "Une prétention frauduleuse automatique", "Une aggravation du risque sans effet"],
      answer: [1],
      explain: "La déclaration inexacte porte sur un fait ayant fait l'objet d'une question précise, et elle a influé sur l'étendue du sinistre : les deux conditions de la réticence sont réunies." },

    { id: 'm3k45', chap: 'c7', type: 'single',
      ctx: "Un fournisseur suisse livre régulièrement à crédit un gros client à l'étranger. Il craint à la fois l'insolvabilité de ce client et l'instabilité du pays concerné.",
      q: "Quelle solution lui proposez-vous ?",
      choices: ["Une assurance-crédit, éventuellement avec couverture du risque politique", "Une protection juridique entreprise", "Un bris de machines", "Une D&O"],
      answer: [0],
      explain: "L'assurance-crédit couvre l'insolvabilité du débiteur ; à l'export, elle peut être complétée par une garantie du risque politique." },

    /* ---------- c8 : souscription et sinistres ---------- */
    { id: 'm3k46', chap: 'c8', type: 'single',
      ctx: "Un commerçant subit un incendie. Ses marchandises détruites valent CHF 90 000.–, le stock total valait CHF 300 000.–, la somme assurée est de CHF 240 000.– et la franchise de CHF 5 000.–. Un tiers est responsable de l'incendie.",
      q: "Quelle indemnité l'assureur verse-t-il, et que peut-il faire ensuite ?",
      choices: ["CHF 85 000.–, sans recours possible", "CHF 67 000.–, puis recours contre le tiers à concurrence de sa prestation", "CHF 90 000.–, puis recours", "CHF 72 000.–, sans recours"],
      answer: [1],
      explain: "Proportionnelle : 90 000 × (240 000/300 000) = CHF 72 000.–. Franchise : 72 000 − 5 000 = CHF 67 000.–. L'assureur est ensuite subrogé jusqu'à concurrence des CHF 67 000.– versés." },

    { id: 'm3k47', chap: 'c8', type: 'single',
      ctx: "Le contrat d'un client imposait l'installation d'une alarme, qu'il n'a jamais fait poser. Des cambrioleurs entrent par une trappe de toit qu'aucune alarme n'aurait pu détecter.",
      q: "L'assureur peut-il réduire sa prestation ?",
      choices: ["Oui, automatiquement de 50 %", "Non : la violation n'a eu aucune influence sur la survenance du sinistre (art. 45 LCA)", "Oui, il peut refuser toute prestation", "Oui, et résilier rétroactivement"],
      answer: [1],
      explain: "L'art. 45 LCA exige une faute ET une influence de la violation sur le sinistre. Ici l'absence d'alarme n'a joué aucun rôle : la prestation est due en entier." },

    { id: 'm3k48', chap: 'c8', type: 'single',
      ctx: "Une cliente déclare un cambriolage. L'enquête établit qu'elle a réellement perdu des biens pour CHF 6 000.–, mais qu'elle a ajouté à sa liste un appareil photo qu'elle n'a jamais possédé, valant CHF 1 800.–.",
      q: "Quelle est la conséquence sur l'ensemble de sa prétention ?",
      choices: ["Elle touche CHF 6 000.–", "Elle perd tout droit aux prestations pour ce sinistre", "Elle touche CHF 7 800.– moins la franchise", "Elle subit une réduction de 23 %"],
      answer: [1],
      explain: "L'art. 40 LCA sanctionne intégralement la prétention frauduleuse : la part honnête tombe également, et l'assureur peut en outre résilier le contrat." },

    { id: 'm3k49', chap: 'c8', type: 'single',
      ctx: "Un sinistre survient le 8 mai. La prime, échue le 1er avril, était impayée ; l'assureur avait envoyé le 20 avril une sommation régulière avec délai de 14 jours et mention des conséquences. Le client règle la prime le 15 mai.",
      q: "Le sinistre du 8 mai est-il couvert ?",
      choices: ["Oui, la prime a finalement été payée", "Non : la couverture était suspendue depuis le 5 mai et la reprise n'a pas d'effet rétroactif", "Oui, à 50 %", "Non, le contrat était déjà résilié"],
      answer: [1],
      explain: "Le délai de 14 jours dès le 20 avril expire le 4 mai ; la suspension court dès le 5 mai. Le paiement tardif ne rétablit la garantie que pour l'avenir." },

    { id: 'm3k50', chap: 'c8', type: 'multi',
      ctx: "Vous devez traiter un dossier de sinistre non-vie complet, comme dans un traitement de cas guidé d'examen.",
      q: "Quelles étapes suivez-vous, et dans quel esprit ?",
      choices: ["Vérifier que le contrat était en vigueur et la couverture non suspendue", "Contrôler que l'événement correspond au risque assuré, sans exclusion précise", "Examiner le respect des obligations et l'existence d'une faute grave", "Calculer l'indemnité : base, sous-assurance, franchise, sous-limites", "Fixer la prime de l'année suivante"],
      answer: [0, 1, 2, 3],
      explain: "La tarification future est une décision de souscription distincte. Le traitement se termine par l'examen d'un éventuel recours contre le tiers responsable." },

    { id: 'm3k51', chap: 'c8', type: 'single',
      ctx: "Une entreprise annonce un sinistre quatre mois après l'avoir constaté. L'assureur a pu instruire le dossier normalement et le retard n'a eu aucune incidence sur l'établissement des faits ni sur l'ampleur du dommage.",
      q: "L'assureur peut-il sanctionner ce retard ?",
      choices: ["Oui, il peut refuser toute prestation", "Non, si la violation n'a eu aucune influence sur la survenance ou l'étendue du sinistre", "Oui, une réduction de moitié s'impose", "Oui, il doit résilier le contrat"],
      answer: [1],
      explain: "L'art. 45 LCA subordonne la sanction à une faute et à une influence effective de la violation : un retard sans conséquence ne justifie aucune réduction." },

    { id: 'm3k52', chap: 'c8', type: 'single',
      ctx: "Un souscripteur examine la demande d'un garage dont la sinistralité des trois dernières années est très défavorable, avec trois incendies mineurs.",
      q: "Quelle décision est la plus proportionnée avant d'envisager un refus ?",
      choices: ["Accepter aux conditions normales", "Accepter avec surprime, franchise majorée ou obligations de prévention", "Refuser immédiatement", "Signaler le client à la FINMA"],
      answer: [1],
      explain: "La souscription dispose de plusieurs leviers : adapter le prix, la participation de l'assuré ou exiger des mesures de protection avant d'en venir au refus." }
  ]);
})();
